#Functions to get extent of an large binary file/small header file pair

#set different paths for testing
path<-"./Original_data/Headwall/MSGC_TST_IMG"
path<-"./Original_data/Headwall/"
path3<-"/Users/peternelson 1/Documents/Schoodic/lecospec_at_schoodic/Git/lecospec/Data/SubsetDatacube"
path<-"/Users/peternelson 1/Documents/Schoodic/lecospec_at_schoodic/Git/lecospec/Data/"
path<-"M:/MSGC_DATA/Deboullie/Imagery/100332_Deboullie_Push_flight_2020_07_21_15_19_27/"

files<-list.files(path)
filenames<- subset(files,grepl(".hdr",files)==TRUE|grepl(".HDR",files)==TRUE)
filenames<-file_path_sans_ext(filenames)  
fileread<-lapply(1:length(filenames), function(x) {raster(paste(path,"/",filenames[x],sep=""))})  
file_crs<-lapply(fileread,crs)  #%>% unlist() 
ext_out<-lapply(fileread, extent) #%>% unlist() %>%
file_list<-list(file_crs,ext_out)

get_extents<- function(path)
{
  files<-list.files(path)
  filenames<- subset(files,grepl(".hdr",files)==TRUE|grepl(".HDR",files)==TRUE)
  filenames<-file_path_sans_ext(filenames)  
  fileread<-lapply(1:length(filenames), function(x) {raster(paste(path,"/",filenames[x],sep=""))})  
  file_crs<-lapply(fileread,crs)  #%>% unlist() 
  ext_out<-lapply(fileread, extent)
  file_list<-list(file_crs,ext_out)
  return(file_list)
}

file_extents<-lapply(path,get_extents)

#UNIT TEST 
file_extents<-unlist(file_extents, recursive = FALSE)
file_crs<-file_extents[[1]] %>% unlist()
file_extents[[2]][[1]] %>% unlist() %>% class()
tst<-as(unlist(file_extents[[2]][[1]]),"SpatialPolygons")
        tst1<-file_extents[[2]][[3]]
            tst_num<-as(tst1@xmin,"numeric");
                if(tst_num==0) "TRUE" else "FALSE"
            
  tst2<-as(unlist(file_extents[[2]][[1]]),"list") #%>% abs() %>% min()
    ifelse(min(abs(tst2))<0, 1, 0)
tst_crs<-unlist(file_extents[[1]][[1]])
crs(tst)<-tst_crs
tst_df<-as(tst,"SpatialPolygonsDataFrame")
  length(tst_df)
  tst_df[,2]#%>% unlist() %>% as.data.frame()
tst_df_proj <- spTransform(tst_df, CRS("+proj=longlat +datum=WGS84"))
writeOGR(tst_df_proj,"tst.kml",layer="tst_df", driver="KML")
#PASS

##Function writes out KMLs of every spatial extent in file_extents generated by prior function
file_polys<-lapply(1:length(file_extents[[2]]), 
                   function(x)
                   { 
                   r<-as(file_extents[[2]][[x]],"SpatialPolygons") 
                   r_crs<-unlist(file_extents[[1]][[x]])
                   crs(r)<-r_crs
                   r_df<-as(r,"SpatialPolygonsDataFrame")
                   r_df_proj <- spTransform(r_df, CRS("+proj=longlat +datum=WGS84"))
                   r_out<-writeOGR(r_df_proj, paste("Flight100332",x,".kml",sep=""),layer=paste("",x,""), driver="KML")
                   return(r_out)
                   })

file_check<-lapply(1:length(file_extents[[2]]), 
                   function(x)
                   { tst1<-as(file_extents[[2]][[x]],"list") %>% min %>% abs
                     #tst1@xmin[1];
                     if(tst1>0) return("TRUE") else "FALSE"})
file_check

file_check_poly<-lapply(1:length(file_extents[[2]]), 
                        function(x)
                        { 
                          check<-as(file_extents[[2]][[x]],"list") %>% min %>% abs
                          #tst1@xmin[1];
                          if(check>0)
                          {r<-as(file_extents[[2]][[x]],"SpatialPolygons") 
                          r_crs<-unlist(file_extents[[1]][[x]])
                          crs(r)<-r_crs
                          r_df<-as(r,"SpatialPolygonsDataFrame")
                          r_df_proj <- spTransform(r_df, CRS("+proj=longlat +datum=WGS84"))
                          r_out<-writeOGR(r_df_proj, paste("Flight100332",x,".kml",sep=""),layer=paste("",x,""), driver="KML")
                          return(r_out)}
                        })
