#Functions to get extent of an large binary file/small header file pair

#set different paths for testing
path<-"./Original_data/Headwall/MSGC_TST_IMG"
path2<-"./Original_data/Headwall/"
path3<-"/Users/peternelson 1/Documents/Schoodic/lecospec_at_schoodic/Git/lecospec/Data/SubsetDatacube"
path4<-"/Users/peternelson 1/Documents/Schoodic/lecospec_at_schoodic/Git/lecospec/Data/"
path5<-"M:/MSGC_DATA/Deboullie/Imagery/100332_Deboullie_Push_flight_2020_07_21_15_19_27"

files<-list.files(path5)
filenames<- subset(files,grepl(".hdr",files)==TRUE|grepl(".HDR",files)==TRUE)
filenames<-file_path_sans_ext(filenames)  
fileread<-lapply(1:length(filenames), function(x) {raster(paste(path5,"/",filenames[x],sep=""))})  
file_crs<-lapply(fileread,crs)  #%>% unlist() 
ext_out<-lapply(fileread, extent) #%>% unlist() %>%
file_list<-list(file_crs,ext_out)

get_extents<- function(path)
{
  files<-list.files(path)
  filenames<- subset(files,grepl(".hdr",files)==TRUE|grepl(".HDR",files)==TRUE)
  filenames<-file_path_sans_ext(filenames)  
  fileread<-lapply(1:length(filenames), function(x) {raster(paste(path5,"/",filenames[x],sep=""))})  
  file_crs<-lapply(fileread,crs)  #%>% unlist() 
  ext_out<-lapply(fileread, extent)
  file_list<-list(file_crs,ext_out)
  return(file_list)
}

file_extents<-lapply(path5,get_extents)

#UNIT TEST 
file_extents<-unlist(file_extents, recursive = FALSE)
file_crs<-file_extents[[1]] %>% unlist()
file_extents[[2]][[1]] %>% unlist() %>% class()
tst<-as(unlist(file_extents[[2]][[1]]),"SpatialPolygons")
tst_crs<-unlist(file_extents[[1]][[1]])
crs(tst)<-tst_crs
tst_df<-as(tst,"SpatialPolygonsDataFrame")
tst_df_proj <- spTransform(tst_df, CRS("+proj=longlat +datum=WGS84"))
writeOGR(tst_df_proj,"tst.kml",layer="tst_df", driver="KML")
#PASS

##Function writes out KMLs of every spatial extent in file_extents generated by prior function
file_polys<-lapply(1:length(file_extents[[2]]), 
                   function(x)
                   { 
                   r<-as(file_extents[[2]][[x]],"SpatialPolygons") 
                   r_crs<-unlist(file_extents[[1]][[x]])
                   crs(r)<-r_crs
                   r_df<-as(r,"SpatialPolygonsDataFrame")
                   r_df_proj <- spTransform(r_df, CRS("+proj=longlat +datum=WGS84"))
                   r_out<-writeOGR(r_df_proj, paste("Flight100332",x,".kml",sep=""),layer=paste("",x,""), driver="KML")
                   return(r_out)
                   })

