#Functions to get extent of a large binary file/small header file pair

library(tidyverse)
library(tools)
library(raster)
library(rgdal)
library(sf)
library(plyr)

####PART 1: Create KML of each flight extent####
# 'path' is a directory that contains orthorectified reflectance data from one flight
###path<-"M:/MSGC_DATA/Deboullie/Imagery/100332_Deboullie_Push_flight_2020_07_21_15_19_27/"
out_put<-"./Outputs/Extents/"

path <- "E:/Tree_Spectral_Library_pjb/PEF_flights/"
#define output paths
indiv_output <- "./Outputs/Extents/"
combined_output <- "./Outputs/Extents/"

#get extents loop
get_extents <- function(path) 
{
  files<-list.files(path)
  #bring in .hdr files
  filenames1<- subset(files,grepl(".hdr",files)==TRUE|grepl(".HDR",files)==TRUE)
  #drop .hdr
  filenames<-file_path_sans_ext(filenames1)  
  #bring in binary files as rasters
  fileread<-lapply(1:length(filenames), function(x) {raster(paste(path,"/",filenames[x],sep=""))})  
  #extract proj and datum from rasters
  ##make this proj6
  file_crs<-lapply(fileread,crs)  #%>% unlist() 
  #extract extents from rasters
  ext_out<-lapply(fileread, extent)
  #combine proj, datum, extent infos
  file_list<-list(file_crs,ext_out)
  return(file_list)
}

#make list from get_extents function
#this is a nested list which carries along both CRS and geometry of flight paths
file_extents<-lapply(path,get_extents)
#reformat list
file_extents<-unlist(file_extents, recursive = FALSE)

##Function writes out KMLs of every spatial extent in file_extents generated by prior function
file_polys<-lapply(1:length(file_extents[[2]]), 
                   function(x)
                   { 
                     r<-as(file_extents[[2]][[x]],"SpatialPolygons") 
                     r_crs<-unlist(file_extents[[1]][[x]])
                     crs(r)<-r_crs
                     r_df<-as(r,"SpatialPolygonsDataFrame")
                     r_df_proj <- spTransform(r_df, CRS("+proj=longlat +datum=WGS84"))
                     r_out<-writeOGR(r_df_proj, paste(indiv_output,"PEF_flight",x,".kml",sep=""),layer=paste("",x,""), driver="KML")
                     return(r_out)
                   })

####PART 2: Combine all KMLs into one####

#this method uses st_read into a list
#uses only geometry from individual flight kmls (no CRS)

#list files in directory
kml_files <- list.files(indiv_output)

#make list of kml inputs
all_kmls_list <- lapply(1:length(kml_files), 
                        function(x) {
                          st_read(paste(indiv_output, "/", kml_files[x], sep = ""))})
#convert to df
all_kmls_df <- do.call(rbind, all_kmls_list)

#write combined KML file
st_write(all_kmls_df, paste(combined_output, "/", "PEF_all.kml", sep = ""), driver = "kml")
st_write(all_kmls_df, paste(combined_output, "/", "PEF_all.shp", sep = ""), driver = "ESRI Shapefile")



#This method uses a script from lecospec
allKmlLayers <- function(kmls){
  lyr <- ogrListLayers(indiv_output)
  mykml <- list()
  for (i in 1:length(lyr)) {
    mykml[i] <- readOGR(indiv_output,lyr[i])
  }
  names(mykml) <- lyr
  return(mykml)
}

kmls1 <- list.files(indiv_output)
kmls <- file_path_sans_ext(kmls1)

dat.out <- data.frame()

for(i in kmls){
  temp <- readOGR(dsn = indiv_output, layer = i)
  dat.out <- rbind(temp, dat.out)
}

ogrListLayers(indiv_output)


all_PEF <- allKmlLayers(indiv_output)

peter_vnir_uas_sf_poly <- do.call(rbind, peter_vnir_uas) %>%
  st_as_sf()

peter_vnir_uas_sf_points <- peter_vnir_uas_sf_poly %>%
  st_centroid()

mapview(peter_vnir_uas_sf_points)


####PART 3: COMBINE KML WITH TREE STEM MAPS####

#read in combined kml
flight_extents <- st_read(paste(combined_output, "/", "PEF_all.kml", sep = ""))

#bring in all point data for tree stem maps
pef_path <- "E:/Tree_Spectral_Library_pjb/Stem_Maps/Field/PEF/"
pef_trees <- list.files(pef_path, recursive = T, pattern = ".shp")
print(pef_trees)

#1. list of .shps with attributes
all_trees_list <- lapply(1:length(pef_trees), 
                         function(x) {
                           st_read(paste(pef_path, "/", pef_trees[x], sep = ""))})

#convert to df
all_trees_df <- do.call(rbind.fill, all_trees_list)


pts_in <- st_join(all_trees_df$geometry, flight_extents$geometry, join = st_within)


#2. separate df for each .shp
for (i in pef_trees) {assign(i, st_read(paste0(pef_path, i)))}


coords <- st_coordinates(all_trees_df)

over(all_trees_df$geometry, flight_extents$geometry)




################################################END############################
##everything below here is old code from PN

#Functions to get extent of an large binary file/small header file pair

#set different paths for testing
#pjb testing
###path<-"M:/MSGC_DATA/Deboullie/Imagery/100332_Deboullie_Push_flight_2020_07_21_15_19_27/"
out_put<-"./Outputs/Extents/"


#path<-"./Original_data/Headwall/MSGC_TST_IMG"
#path<-"./Original_data/Headwall/"
#path3<-"/Users/peternelson 1/Documents/Schoodic/lecospec_at_schoodic/Git/lecospec/Data/SubsetDatacube"
#path<-"/Users/peternelson 1/Documents/Schoodic/lecospec_at_schoodic/Git/lecospec/Data/"
###path<-"M:/MSGC_DATA/Deboullie/Imagery/100332_Deboullie_Push_flight_2020_07_21_15_19_27/"
#out_put<-"./Outputs/2_Imagery/Headwall/Extents/"
out_put<-"./Outputs/Extents/"

files<-list.files(path)
#filenames<-subset(files,grepl("^raw",files)==TRUE)
filenames<- subset(files,grepl(".hdr",files)==TRUE&grepl("^raw",files)|grepl(".HDR",files)==TRUE&grepl("^raw",files))
filenames<-lapply(1:length(filenames),function(x) {str_split(filenames[x], ".hdr")}) %>% unlist(recursive = FALSE) %>% as.data.frame() %>% t() %>% as.data.frame() %>% dplyr::select(1) 
#fileread<-lapply(1:length(filenames), function(x) {raster(paste(path,filenames[x],".hdr",sep=""))})  
rownames(filenames)<-NULL
filenames[1,1]
fileread<-lapply(1:nrow(filenames), function(x) {raster(paste(path,filenames[x,1],sep=""))})  

file_crs<-lapply(fileread,crs)  #%>% unlist() 
ext_out<-lapply(fileread, extent) #%>% unlist() %>%
file_list<-list(file_crs,ext_out)

#get extents loop
get_extents<- function(path)
{
  files<-list.files(path)
  filenames<- subset(files,grepl(".hdr",files)==TRUE|grepl(".HDR",files)==TRUE)
  filenames<-file_path_sans_ext(filenames)  
  fileread<-lapply(1:length(filenames), function(x) {raster(paste(path,"/",filenames[x],sep=""))})  
  file_crs<-lapply(fileread,crs)  #%>% unlist() 
  ext_out<-lapply(fileread, extent)
  file_list<-list(file_crs,ext_out)
  return(file_list)
}

file_extents<-lapply(path,get_extents)

#UNIT TEST 
file_extents<-unlist(file_extents, recursive = FALSE)
file_crs<-file_extents[[1]] %>% unlist()
file_extents[[2]][[1]] %>% unlist() %>% class()
tst<-as(unlist(file_extents[[2]][[1]]),"SpatialPolygons")
tst1<-file_extents[[2]][[3]]
tst_num<-as(tst1@xmin,"numeric");
if(tst_num==0) "TRUE" else "FALSE"

tst2<-as(unlist(file_extents[[2]][[1]]),"list") #%>% abs() %>% min()
ifelse(min(abs(tst2))<0, 1, 0)
tst_crs<-unlist(file_extents[[1]][[1]])
crs(tst)<-tst_crs
tst_df<-as(tst,"SpatialPolygonsDataFrame")
length(tst_df)
tst_df[,2]#%>% unlist() %>% as.data.frame()
tst_df_proj <- spTransform(tst_df, CRS("+proj=longlat +datum=WGS84"))
writeOGR(tst_df_proj,"tst.kml",layer="tst_df", driver="KML")
#PASS

##Function writes out KMLs of every spatial extent in file_extents generated by prior function
file_polys<-lapply(1:length(file_extents[[2]]), 
                   function(x)
                   { 
                     r<-as(file_extents[[2]][[x]],"SpatialPolygons") 
                     r_crs<-unlist(file_extents[[1]][[x]])
                     crs(r)<-r_crs
                     r_df<-as(r,"SpatialPolygonsDataFrame")
                     r_df_proj <- spTransform(r_df, CRS("+proj=longlat +datum=WGS84"))
                     r_out<-writeOGR(r_df_proj, paste(out_put,"Flight100332",x,".kml",sep=""),layer=paste("",x,""), driver="KML")
                     return(r_out)
                   })

file_polys_merge<-Reduce(raster::merge, file_polys)
file_check<-lapply(1:length(file_extents[[2]]), 
                   function(x)
                   { tst1<-as(file_extents[[2]][[x]],"list") %>% min %>% abs
                   #tst1@xmin[1];
                   if(tst1>0) return("TRUE") else "FALSE"})
file_check

file_check_poly<-lapply(1:length(file_extents[[2]]), 
                        function(x)
                        { 
                          check<-as(file_extents[[2]][[x]],"list") %>% min %>% abs
                          #tst1@xmin[1];
                          if(check>0)
                          {r<-as(file_extents[[2]][[x]],"SpatialPolygons") 
                          r_crs<-unlist(file_extents[[1]][[x]])
                          crs(r)<-r_crs
                          r_df<-as(r,"SpatialPolygonsDataFrame")
                          r_df_proj <- spTransform(r_df, CRS("+proj=longlat +datum=WGS84"))
                          r_out<-writeOGR(r_df_proj, paste("Flight100332",x,".kml",sep=""),layer=paste("",x,""), driver="KML")
                          return(r_out)}
                        })
